<?php
error_reporting(0);
date_default_timezone_set("Asia/Tehran");

$Channel = [
    "V2rayNGn",
    "free4allVPN",
    "PrivateVPNs",
    "DirectVPN",
    "ProxyFn",
    "v2ray_outlineir",
    "NetAccount",
    "oneclickvpnkeys",
    "daorzadannet",
    "Outline_Vpn",
    "vpn_xw",
    "prrofile_purple",
    "ShadowSocks_s",
    "azadi_az_inja_migzare",
    "WomanLifeFreedomVPN",
    "internet4iran",
    "LegenderY_Servers",
    "vpnfail_v2ray",
    "UnlimitedDev",
    "vmessorg",
    "v2rayNG_Matsuri",
    "v2rayngvpn",
    "vpn_ioss",
    "v2freevpn",
    "customv2ray",
    "FalconPolV2rayNG",
    "Jeyksatan",
    "hassan_saboorii",
    "v2rayvmess",
    "v2rayNGNeT",
    "server01012",
    "ShadowProxy66",
    "ipV2Ray",
    "kiava",
    "Helix_Servers",
    "PAINB0Y",
    "VpnProSec",
    "VlessConfig",
    "NIM_VPN_ir",
];
$Types = [
    "V2rayNGn" => ["vmess", "vless"],
    "free4allVPN" => ["vmess", "ss"],
    "PrivateVPNs" => ["trojan"],
    "DirectVPN" => ["trojan"],
    "ProxyFn" => ["vless"],
    "v2ray_outlineir" => ["vmess"],
    "NetAccount" => ["trojan"],
    "oneclickvpnkeys" => ["vmess", "trojan"],
    "daorzadannet" => ["vmess", "vless"],
    "Outline_Vpn" => ["vless"],
    "vpn_xw" => ["vless"],
    "prrofile_purple" => ["vmess", "vless"],
    "ShadowSocks_s" => ["vless"],
    "azadi_az_inja_migzare" => ["vless", "ss"],
    "WomanLifeFreedomVPN" => ["vless"],
    "internet4iran" => ["vless"],
    "customv2ray" => ["vmess", "vless"],
    "LegenderY_Servers" => ["vless"],
    "vpnfail_v2ray" => ["vmess"],
    "UnlimitedDev" => ["vless"],
    "vmessorg" => ["vmess", "vless"],
    "v2rayNG_Matsuri" => ["vless"],
    "v2rayngvpn" => ["vless"],
    "vpn_ioss" => ["vmess"],
    "v2freevpn" => ["vless"],
    "customv2ray" => ["vmess", "vless"],
    "FalconPolV2rayNG" => ["vless"],
    "Jeyksatan" => ["vmess", "trojan"],
    "hassan_saboorii" => ["vmess", "vless"],
    "v2rayvmess" => ["vmess", "vless"],
    "v2rayNGNeT" => ["vless"],
    "server01012" => ["vmess"]و
    "ShadowProxy66" => ["vmess", "vless"],
    "ipV2Ray" => ["vless"],
    "kiava" => ["vless"],
    "Helix_Servers" => ["vless"],
    "PAINB0Y" => ["vless"],
    "VpnProSec" => ["vless"],
    "VlessConfig" => ["vless"],
    "NIM_VPN_ir" => ["vless"],
];

?>
